language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mmkrasko/docker-frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true mmkrasko/docker-frontend npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-frontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-900561060496"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY